//------------------------------------------------------------------------------
// <auTo-generated>
//     This code was generated by a Tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes To this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auTo-generated>
//------------------------------------------------------------------------------

namespace MailSender.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.EdiTors.SettingsDesigner.SettingsSingleFileGeneraTor", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
    }
}
